# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요1
# defaultZone: http://localhost:8761/eureka/  => eureka 서버의 위치정보 명시
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8841/eureka/

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
#  application: 각자가 가지고있으니...
#    name: member-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:7777}
      password: GODLOVEME
  # 구버전 경로 참조용으로 추가 , 로컬 7777, ec2에서는 compose.yml에 환경변수값으로..
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:7777}
    password: GODLOVEME
  jpa:
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.example.msa_db_sep_hst: DEBUG

jwt:
  expiration: 140
  expirationRt: 1500